### PR TITLE
install instructions and minor file edits

### PR DESCRIPTION
**Pull request by securelyfitz**
updating urls and instructions for setup. Also adding #! and +x to py files for ease of use.

### CODE REVIEW

**Comment by cr1901** [comment]
This all looks fine to me (don't want to merge on @esden's behalf tho).

**Comment by esden** [comment]
This looks good! Thank you. Can you get rid of the merge commit aka. rebase cleanly on top of master? Then I will merge it.

**Comment by securelyfitz** [comment]
sure, once i figure out how.

**Comment by esden** [comment]
Thank you very much for your contribution. Merged with: ebced310868c8999cf1f93138da8dfe053107613

**Pull request closed without merging**
